fix(input-elements): fix value property in input elements
concordialang/ui-core pull request #7
Opened 2019-04-03 14:58 UTC by vcpablo

2019-04-05 18:17 UTC, thiagodp approved these changes

2019-04-09 01:03 UTC, thiagodp commented on src/interfaces/prototyper.ts
> +import { HtmlElement } from '../../../ui-html/src/classes/html-elements';
Is this import right? Is really `ui-core` importing from `ui-html` ?

2019-04-09 14:51 UTC, WillianGoncalves requested changes
The `ui-core` should not import `ui-html`.

2019-04-10 01:22 UTC, WillianGoncalves approved these changes

2019-04-10 03:02 UTC, merged